'use client'

import { useEffect, useState } from 'react'
import { LockKeyhole, Save, ShieldCheck } from 'lucide-react'
import { PageHeader } from '@/components/layout/PageHeader'
import { profileService } from '@/features/profile/services/profile-service'
import type { SellerProfileData } from '@/features/profile/types/profile.types'

export function SettingsPage() {
  const [profile, setProfile] = useState<SellerProfileData>()
  const [form, setForm] = useState({ name: '', email: '', phone: '', businessName: '' })
  const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' })
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [notice, setNotice] = useState<{ type: 'success' | 'error'; text: string }>()

  useEffect(() => { profileService.getSellerProfile().then((data) => { setProfile(data); setForm({ name: data.user.name, email: data.user.email, phone: data.user.phone, businessName: data.vendor.businessName }) }).catch((error) => setNotice({ type: 'error', text: error instanceof Error ? error.message : 'Unable to load settings' })).finally(() => setLoading(false)) }, [])
  const saveProfile = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setNotice(undefined); try { const [user, vendor] = await Promise.all([profileService.updateUserProfile({ name: form.name, email: form.email, phone: form.phone }), profileService.updateVendorProfile({ businessName: form.businessName })]); setProfile({ user, vendor }); setNotice({ type: 'success', text: 'Account and store settings saved.' }) } catch (error) { setNotice({ type: 'error', text: error instanceof Error ? error.message : 'Unable to save settings' }) } finally { setSaving(false) } }
  const changePassword = async (event: React.FormEvent) => { event.preventDefault(); setNotice(undefined); if (password.newPassword !== password.confirmPassword) { setNotice({ type: 'error', text: 'New passwords do not match.' }); return } if (password.newPassword.length < 8) { setNotice({ type: 'error', text: 'New password must be at least 8 characters.' }); return } setSaving(true); try { await profileService.changePassword(password.currentPassword, password.newPassword); setPassword({ currentPassword: '', newPassword: '', confirmPassword: '' }); setNotice({ type: 'success', text: 'Password changed. Other active sessions were signed out.' }) } catch (error) { setNotice({ type: 'error', text: error instanceof Error ? error.message : 'Unable to change password' }) } finally { setSaving(false) } }
  if (loading) return <main className="workspace"><p className="subtle">Loading settings…</p></main>
  if (!profile) return <main className="workspace"><div className="auth-notice error">{notice?.text || 'Settings unavailable.'}</div></main>
  return <main className="workspace settings-page"><PageHeader eyebrow="Account controls" title="Settings" description="Manage your account details, store identity, and session security." />{notice && <div className={`auth-notice ${notice.type}`} role={notice.type === 'error' ? 'alert' : 'status'}>{notice.text}</div>}<div className="settings-grid"><section className="panel profile-card"><div className="panel-heading"><div><h2>Account and store</h2><p>These details are saved to your seller account.</p></div><ShieldCheck className="heading-icon" /></div><form className="settings-form" onSubmit={saveProfile}><label><span>Full name</span><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label><span>Email</span><input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label><span>Phone</span><input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><label><span>Business name</span><input required value={form.businessName} onChange={(event) => setForm({ ...form, businessName: event.target.value })} /></label><button className="primary-button" disabled={saving}><Save /> Save account settings</button></form></section><section className="panel profile-card"><div className="panel-heading"><div><h2>Security</h2><p>Change your password using your current credentials.</p></div><LockKeyhole className="heading-icon" /></div><form className="settings-form" onSubmit={changePassword}><label><span>Current password</span><input required type="password" autoComplete="current-password" value={password.currentPassword} onChange={(event) => setPassword({ ...password, currentPassword: event.target.value })} /></label><label><span>New password</span><input required minLength={8} type="password" autoComplete="new-password" value={password.newPassword} onChange={(event) => setPassword({ ...password, newPassword: event.target.value })} /></label><label><span>Confirm new password</span><input required minLength={8} type="password" autoComplete="new-password" value={password.confirmPassword} onChange={(event) => setPassword({ ...password, confirmPassword: event.target.value })} /></label><button className="secondary-button" disabled={saving}><LockKeyhole /> Change password</button></form></section></div></main>
}
